
package pom.xml.gui;

import java.awt.BorderLayout;
import java.io.File;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import pom.xml.AppConfig;
import pom.xml.sql.SQLExecutor;
import pom.xml.sql.SQLGenerator;
import pom.xml.utils.FileReader;

public class GUI extends javax.swing.JFrame {
    
    private SQLExecutor sqlExecutor;
    private AppConfig appConfig;
    private final char sep = File.separatorChar;
    private final String schemaPathComplement = "src" + sep + "main" + sep + "resources" + sep;
    private final String appLocalPath = System.getProperty("user.dir") + sep + schemaPathComplement;
    
    
    public GUI() {
        initComponents();
        appConfig = new AppConfig();
        sqlExecutor = new SQLExecutor(appConfig);
        
        setTitle("API Sample by Mariana Tebecherani");
        setSize(805,590);
        setResizable(false);
        setLayout(new BorderLayout());
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        jTxtAreaSchema.setText(appConfig.getDbSchema());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlSchema = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAreaSchema = new javax.swing.JTextArea();
        jBtnLoadSchema = new javax.swing.JButton();
        jPnlQuestion = new javax.swing.JPanel();
        jTxtQuestion = new javax.swing.JTextField();
        jBtnSend = new javax.swing.JButton();
        jPnlAnswer = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtAreaAnswer = new javax.swing.JTextArea();
        jPnlNote = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnlSchema.setBorder(javax.swing.BorderFactory.createTitledBorder("Reference Database Schema:"));

        jTxtAreaSchema.setEditable(false);
        jTxtAreaSchema.setColumns(20);
        jTxtAreaSchema.setRows(5);
        jScrollPane1.setViewportView(jTxtAreaSchema);

        jBtnLoadSchema.setText("Load Database Schema");
        jBtnLoadSchema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoadSchemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlSchemaLayout = new javax.swing.GroupLayout(jPnlSchema);
        jPnlSchema.setLayout(jPnlSchemaLayout);
        jPnlSchemaLayout.setHorizontalGroup(
            jPnlSchemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlSchemaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnLoadSchema)
                .addContainerGap())
        );
        jPnlSchemaLayout.setVerticalGroup(
            jPnlSchemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlSchemaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlSchemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlSchemaLayout.createSequentialGroup()
                        .addComponent(jBtnLoadSchema)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPnlQuestion.setBorder(javax.swing.BorderFactory.createTitledBorder("Question:"));

        jBtnSend.setText("Send");
        jBtnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlQuestionLayout = new javax.swing.GroupLayout(jPnlQuestion);
        jPnlQuestion.setLayout(jPnlQuestionLayout);
        jPnlQuestionLayout.setHorizontalGroup(
            jPnlQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTxtQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSend)
                .addContainerGap())
        );
        jPnlQuestionLayout.setVerticalGroup(
            jPnlQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSend))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPnlAnswer.setBorder(javax.swing.BorderFactory.createTitledBorder("Answer:"));

        jTxtAreaAnswer.setEditable(false);
        jTxtAreaAnswer.setColumns(20);
        jTxtAreaAnswer.setRows(5);
        jScrollPane2.setViewportView(jTxtAreaAnswer);

        javax.swing.GroupLayout jPnlAnswerLayout = new javax.swing.GroupLayout(jPnlAnswer);
        jPnlAnswer.setLayout(jPnlAnswerLayout);
        jPnlAnswerLayout.setHorizontalGroup(
            jPnlAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAnswerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPnlAnswerLayout.setVerticalGroup(
            jPnlAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAnswerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPnlNote.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText(" to configure Ollama, change the app.config file.");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Note:");

        javax.swing.GroupLayout jPnlNoteLayout = new javax.swing.GroupLayout(jPnlNote);
        jPnlNote.setLayout(jPnlNoteLayout);
        jPnlNoteLayout.setHorizontalGroup(
            jPnlNoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlNoteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(415, Short.MAX_VALUE))
        );
        jPnlNoteLayout.setVerticalGroup(
            jPnlNoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlNoteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlNoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnlQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnlSchema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnlAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPnlNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnlSchema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnlAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnlNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLoadSchemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoadSchemaActionPerformed
        
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File(appLocalPath));
        try{
            int resp = fc.showOpenDialog(null);
            if(resp == JFileChooser.APPROVE_OPTION){                
                File file = fc.getSelectedFile();
                FileReader fr = new FileReader();
                String content = fr.convertTextFileToString(file.getAbsolutePath());
                jTxtAreaSchema.setText(content);
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_jBtnLoadSchemaActionPerformed

    private void jBtnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSendActionPerformed
        
        SQLGenerator sqlGenerator = new SQLGenerator(appConfig);
        String sqlQuery = sqlGenerator.getSQL(jTxtQuestion.getText(), jTxtAreaSchema.getText());
        //String resultSQLQuery = sqlExecutor.resultFromSqlQuery(sqlQuery);
        jTxtAreaAnswer.setText(sqlQuery);
 
    }//GEN-LAST:event_jBtnSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLoadSchema;
    private javax.swing.JButton jBtnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPnlAnswer;
    private javax.swing.JPanel jPnlNote;
    private javax.swing.JPanel jPnlQuestion;
    private javax.swing.JPanel jPnlSchema;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTxtAreaAnswer;
    private javax.swing.JTextArea jTxtAreaSchema;
    private javax.swing.JTextField jTxtQuestion;
    // End of variables declaration//GEN-END:variables
}
